export const styles = {
  hero: () => ({
    flex: 1,
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    padding: '5rem 2rem 3rem',
    textAlign: 'center' as const,
    background: 'radial-gradient(ellipse 80% 50% at 50% 0%, rgba(200,98,42,0.07) 0%, transparent 70%)',
    position: 'relative' as const,
  }),
  dotGrid: () => ({
    content: '""',
    position: 'absolute' as const,
    inset: 0,
    backgroundImage: 'radial-gradient(circle, rgba(0,0,0,0.14) 1px, transparent 1px)',
    backgroundSize: '28px 28px',
    opacity: 0.35,
    pointerEvents: 'none' as const,
  }),
  eyebrow: () => ({
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    background: 'var(--white)',
    border: '1px solid var(--border2)',
    borderRadius: '2rem',
    padding: '0.35rem 1rem',
    fontSize: '0.78rem',
    color: 'var(--text2)',
    marginBottom: '2rem',
    boxShadow: 'var(--shadow)',
  }),
  h1: () => ({
    fontFamily: "'Syne', sans-serif",
    fontSize: 'clamp(3rem, 6.5vw, 5.5rem)',
    fontWeight: 700,
    lineHeight: 1.05,
    letterSpacing: '-0.04em',
    maxWidth: '800px',
    marginBottom: '1.25rem',
    color: 'var(--text)',
    position: 'relative' as const,
  }),
  accent: () => ({
    color: 'var(--accent)',
  }),
  subtitle: () => ({
    fontSize: '1.05rem',
    color: 'var(--text2)',
    maxWidth: '500px',
    marginBottom: '3rem',
    fontWeight: 400,
    lineHeight: 1.6,
  }),
};
