export const styles = {
  section: () => ({
    padding: '3.5rem 2.5rem',
    background: 'linear-gradient(135deg, var(--text) 0%, #2D2A24 100%)',
    textAlign: 'center' as const,
  }),
  inner: () => ({
    maxWidth: '560px',
    margin: '0 auto',
  }),
  eyebrow: () => ({
    fontSize: '0.72rem',
    fontWeight: 700,
    letterSpacing: '0.12em',
    textTransform: 'uppercase' as const,
    color: 'var(--accent)',
    marginBottom: '0.75rem',
  }),
  heading: () => ({
    fontFamily: "'Syne', sans-serif",
    fontSize: 'clamp(1.6rem, 3vw, 2.4rem)',
    fontWeight: 700,
    letterSpacing: '-0.03em',
    color: 'white',
    marginBottom: '0.75rem',
    lineHeight: 1.2,
  }),
  subtitle: () => ({
    fontSize: '0.9rem',
    color: 'rgba(255,255,255,0.6)',
    marginBottom: '2rem',
    lineHeight: 1.6,
  }),
  formRow: () => ({
    display: 'flex',
    gap: '8px',
    justifyContent: 'center',
    flexWrap: 'wrap' as const,
    marginBottom: '1.5rem',
  }),
  input: () => ({
    flex: 1,
    minWidth: '220px',
    maxWidth: '320px',
    padding: '0.7rem 1.1rem',
    borderRadius: '2rem',
    border: '1.5px solid rgba(255,255,255,0.15)',
    background: 'rgba(255,255,255,0.08)',
    color: 'white',
    fontFamily: "'Instrument Sans', sans-serif",
    fontSize: '0.88rem',
    outline: 'none',
  }),
  submitBtn: () => ({
    background: 'var(--accent)',
    color: 'white',
    border: 'none',
    padding: '0.7rem 1.5rem',
    borderRadius: '2rem',
    fontFamily: "'Instrument Sans', sans-serif",
    fontSize: '0.88rem',
    fontWeight: 600,
    cursor: 'pointer',
    whiteSpace: 'nowrap' as const,
    transition: 'background 0.2s',
  }),
  disclaimer: () => ({
    fontSize: '0.72rem',
    color: 'rgba(255,255,255,0.35)',
  }),
};
