export const styles = {
  section: () => ({
    padding: '4rem 2.5rem',
    background: 'var(--white)',
  }),
  inner: () => ({
    maxWidth: '1840px',
    margin: '0 auto',
  }),
  header: () => ({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '1.75rem',
  }),
  title: () => ({
    fontFamily: "'Syne', sans-serif",
    fontSize: 'clamp(1.25rem, 2.5vw, 1.75rem)',
    fontWeight: 700,
    letterSpacing: '-0.03em',
    color: 'var(--text)',
  }),
  viewLink: () => ({
    fontSize: '0.82rem',
    color: 'var(--accent)',
    cursor: 'pointer',
    fontWeight: 500,
    background: 'none',
    border: 'none',
    fontFamily: "'Instrument Sans', sans-serif",
  }),
  grid: () => ({
    display: 'grid',
    gridTemplateColumns: 'repeat(6, 1fr)',
    gap: '1rem',
  }),
  card: () => ({
    background: 'var(--white)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-lg)',
    padding: '1.25rem',
    cursor: 'pointer',
    transition: 'all 0.2s',
    '&:hover': {
      boxShadow: 'var(--shadow-md)',
      borderColor: 'var(--accent-border)',
    },
  }),
  cardMeta: () => ({
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '0.75rem',
  }),
  badge: () => ({
    display: 'inline-flex',
    alignItems: 'center',
    padding: '0.2rem 0.6rem',
    borderRadius: '2rem',
    fontSize: '0.68rem',
    fontWeight: 700,
    whiteSpace: 'nowrap' as const,
  }),
  labText: () => ({
    fontSize: '0.72rem',
    color: 'var(--text3)',
  }),
  cardTitle: () => ({
    fontFamily: "'Syne', sans-serif",
    fontSize: '0.95rem',
    fontWeight: 700,
    color: 'var(--text)',
    marginBottom: '0.35rem',
    letterSpacing: '-0.01em',
  }),
  cardDesc: () => ({
    fontSize: '0.82rem',
    color: 'var(--text2)',
    lineHeight: 1.55,
  }),
};
