export const styles = {
  nav: () => ({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '1rem 2.5rem',
    background: 'rgba(244,242,238,0.92)',
    backdropFilter: 'blur(14px)',
    borderBottom: '1px solid var(--border)',
    position: 'sticky' as const,
    top: 0,
    zIndex: 200,
  }),
  logo: () => ({
    fontFamily: "'Syne', sans-serif",
    fontSize: '1.4rem',
    fontWeight: 700,
    letterSpacing: '-0.03em',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    cursor: 'pointer',
    color: 'var(--text)',
    userSelect: 'none' as const,
  }),
  logoMark: () => ({
    width: '26px',
    height: '26px',
    background: 'var(--accent)',
    borderRadius: '6px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  }),
  navLinks: () => ({
    display: 'flex',
    alignItems: 'center',
    gap: '1.75rem',
    listStyle: 'none',
    margin: 0,
    padding: 0,
  }),
  navLink: () => ({
    fontSize: '0.85rem',
    color: 'var(--text2)',
    textDecoration: 'none',
    transition: 'color 0.2s',
    cursor: 'pointer',
    fontFamily: "'Instrument Sans', sans-serif",
    '&:hover': { color: 'var(--text)' },
  }),
  navActions: () => ({
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    position: 'relative' as const,
  }),
  langBtn: () => ({
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '0.35rem 0.75rem',
    background: 'transparent',
    border: '1px solid var(--border2)',
    borderRadius: '2rem',
    fontSize: '0.78rem',
    fontWeight: 600,
    color: 'var(--text2)',
    cursor: 'pointer',
    fontFamily: "'Instrument Sans', sans-serif",
    transition: 'all 0.2s',
  }),
  langMenu: () => ({
    position: 'absolute' as const,
    top: 'calc(100% + 8px)',
    right: 0,
    background: 'var(--white)',
    border: '1px solid var(--border2)',
    borderRadius: 'var(--radius)',
    boxShadow: 'var(--shadow-lg)',
    minWidth: '200px',
    zIndex: 999,
    overflow: 'hidden',
    padding: '0.5rem',
  }),
  langMenuHead: () => ({
    fontSize: '0.7rem',
    fontWeight: 700,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.08em',
    color: 'var(--text3)',
    padding: '0.35rem 0.5rem 0.5rem',
  }),
  langOpt: () => ({
    display: 'block',
    width: '100%',
    padding: '0.4rem 0.5rem',
    fontSize: '0.82rem',
    color: 'var(--text2)',
    background: 'none',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    textAlign: 'left' as const,
    fontFamily: "'Instrument Sans', sans-serif",
    transition: 'all 0.15s',
  }),
  btnGhost: () => ({
    background: 'none',
    border: '1px solid var(--border2)',
    color: 'var(--text)',
    fontFamily: "'Instrument Sans', sans-serif",
    borderRadius: '2rem',
    padding: '0.55rem 1.25rem',
    fontSize: '0.85rem',
    fontWeight: 500,
    cursor: 'pointer',
    transition: 'all 0.2s',
  }),
  btnPrimary: () => ({
    background: 'var(--accent)',
    color: 'white',
    border: 'none',
    fontFamily: "'Instrument Sans', sans-serif",
    borderRadius: '2rem',
    padding: '0.55rem 1.25rem',
    fontSize: '0.85rem',
    fontWeight: 500,
    cursor: 'pointer',
    transition: 'all 0.2s',
  }),
};
