export const styles = {
  section: () => ({
    padding: '4rem 2.5rem',
    background: 'var(--bg)',
  }),
  inner: () => ({
    maxWidth: '1840px',
    margin: '0 auto',
  }),
  header: () => ({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '1rem',
  }),
  title: () => ({
    fontFamily: "'Syne', sans-serif",
    fontSize: 'clamp(1.25rem, 2.5vw, 1.75rem)',
    fontWeight: 700,
    letterSpacing: '-0.03em',
    color: 'var(--text)',
  }),
  compareLink: () => ({
    fontSize: '0.82rem',
    color: 'var(--accent)',
    cursor: 'pointer',
    fontWeight: 500,
    background: 'none',
    border: 'none',
    fontFamily: "'Instrument Sans', sans-serif",
  }),
  subtitle: () => ({
    fontSize: '0.88rem',
    color: 'var(--text2)',
    marginBottom: '1.75rem',
    maxWidth: '620px',
  }),
  tableWrapper: () => ({
    overflowX: 'auto' as const,
    borderRadius: 'var(--radius-lg)',
    border: '1px solid var(--border)',
    background: 'var(--white)',
    boxShadow: 'var(--shadow)',
  }),
  table: () => ({
    width: '100%',
    borderCollapse: 'collapse' as const,
    fontSize: '0.82rem',
    minWidth: '720px',
  }),
  theadRow: () => ({
    borderBottom: '2px solid var(--border)',
    background: 'var(--bg)',
  }),
  th: () => ({
    textAlign: 'left' as const,
    padding: '0.85rem 1.25rem',
    fontFamily: "'Syne', sans-serif",
    fontSize: '0.78rem',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
    color: 'var(--text3)',
    fontWeight: 700,
  }),
  thCenter: () => ({
    textAlign: 'center' as const,
    padding: '0.85rem 1rem',
    fontFamily: "'Syne', sans-serif",
    fontSize: '0.78rem',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
    color: 'var(--text3)',
    fontWeight: 700,
  }),
  tdRow: () => ({
    borderBottom: '1px solid var(--border)',
    transition: 'background 0.15s',
    cursor: 'pointer',
    '&:hover': { background: 'var(--bg)' },
    '&:last-child': { borderBottom: 'none' },
  }),
  td: () => ({
    padding: '0.8rem 1.25rem',
    color: 'var(--text2)',
    verticalAlign: 'middle' as const,
  }),
  tdCenter: () => ({
    padding: '0.8rem 1rem',
    color: 'var(--text2)',
    textAlign: 'center' as const,
    verticalAlign: 'middle' as const,
    fontSize: '1rem',
  }),
  modelNameWrap: () => ({
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  }),
  modelIcon: () => ({
    fontSize: '1rem',
  }),
  modelName: () => ({
    fontWeight: 600,
    fontSize: '0.85rem',
    color: 'var(--text)',
  }),
  tdOrg: () => ({
    padding: '0.8rem 1rem',
    color: 'var(--text3)',
    fontSize: '0.8rem',
    verticalAlign: 'middle' as const,
  }),
  tdContext: () => ({
    padding: '0.8rem 1rem',
    textAlign: 'center' as const,
    fontSize: '0.8rem',
    fontWeight: 500,
    color: 'var(--blue)',
    verticalAlign: 'middle' as const,
  }),
  tdPrice: () => ({
    padding: '0.8rem 1rem',
    textAlign: 'center' as const,
    fontSize: '0.8rem',
    fontWeight: 600,
    color: 'var(--teal)',
    verticalAlign: 'middle' as const,
  }),
  tdSpeed: (speed: string) => ({
    padding: '0.8rem 1rem',
    textAlign: 'center' as const,
    fontSize: '0.8rem',
    fontWeight: 500,
    verticalAlign: 'middle' as const,
    color: speed === '🟢 Fast' ? 'var(--green)'
      : speed === '⚡ Fastest' ? 'var(--accent)'
      : speed === '🟠 Moderate' ? 'var(--amber)'
      : 'var(--rose)',
  }),
  tdBestFor: () => ({
    padding: '0.8rem 1.25rem',
    fontSize: '0.78rem',
    color: 'var(--text2)',
    verticalAlign: 'middle' as const,
  }),
  disclaimer: () => ({
    marginTop: '1rem',
    fontSize: '0.75rem',
    color: 'var(--text3)',
  }),
};
