export const styles = {
  section: () => ({
    padding: '4rem 2.5rem',
    background: 'var(--white)',
  }),
  inner: () => ({
    maxWidth: '1840px',
    margin: '0 auto',
  }),
  header: () => ({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '1.75rem',
  }),
  title: () => ({
    fontFamily: "'Syne', sans-serif",
    fontSize: 'clamp(1.25rem, 2.5vw, 1.75rem)',
    fontWeight: 700,
    letterSpacing: '-0.03em',
    color: 'var(--text)',
  }),
  browseLink: () => ({
    fontSize: '0.82rem',
    color: 'var(--accent)',
    cursor: 'pointer',
    fontWeight: 500,
    transition: 'color 0.2s',
    whiteSpace: 'nowrap' as const,
    background: 'none',
    border: 'none',
    fontFamily: "'Instrument Sans', sans-serif",
  }),
  grid: () => ({
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))',
    gap: '1rem',
  }),
  card: () => ({
    background: 'var(--white)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius)',
    padding: '1.25rem',
    cursor: 'pointer',
    transition: 'all 0.2s',
    '&:hover': {
      boxShadow: 'var(--shadow)',
      borderColor: 'var(--accent-border)',
    },
  }),
  cardTop: () => ({
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: '0.75rem',
  }),
  cardBadge: () => ({
    display: 'inline-flex',
    alignItems: 'center',
    gap: '5px',
    padding: '0.2rem 0.6rem',
    borderRadius: '2rem',
    fontSize: '0.68rem',
    fontWeight: 700,
  }),
  cardTitle: () => ({
    fontFamily: "'Syne', sans-serif",
    fontSize: '0.95rem',
    fontWeight: 700,
    color: 'var(--text)',
    marginBottom: '0.3rem',
    letterSpacing: '-0.01em',
  }),
  cardDesc: () => ({
    fontSize: '0.8rem',
    color: 'var(--text2)',
    lineHeight: 1.5,
    marginBottom: '0.75rem',
  }),
  cardFooter: () => ({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    fontSize: '0.72rem',
    color: 'var(--text3)',
  }),
  ratingBadge: () => ({
    background: 'var(--accent-lt)',
    color: 'var(--accent)',
    padding: '0.18rem 0.5rem',
    borderRadius: '2rem',
    fontWeight: 700,
    fontSize: '0.72rem',
  }),
};
